### ISSUE TITLE
Error with small file

### ISSUE THREAD

**Issue by Catsy73** [rokups/zinc#1] opened 2019-01-12 13:51 UTC
Hello,

First, thanks for your work, it's a very interesting project.

I think I found a bug with when you hash small files.
I get the following error:
```
[terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
```

I understand that sync small file is not the goal of this project, but I would like to make an updater based on your library and I have small files to sync.

Cdly,
Catsy

Edit: I'm under Windows 10 compile with MinGW-W64 v7.2.0

**Comment by rokups** [comment] 2019-01-12 13:59
Hey,
Thanks for taking interest!

Syncing small files indeed is beyond the scope of this library, but nevertheless it should not crash. Could you provide more information on how to reproduce the issue?

Using this library on small files is pretty much pointless because metadata for extremely tiny files would be larger than files themselves, while files of several MB are likely to be split into a single chunk making use of library pointless as it would simply instruct you to download entire file.

⚠️ Word of warning ⚠️: chances are this code is likely not very reliable. There likely are obscure edgecases that might corrupt files. Good thing is that in case of corruption file can be fixed by re-running update on broken file. Should you come upon these cases where file gets corrupted - please do share both updated and old files so i could reproduce the issue and fix it.

**Comment by Catsy73** [comment] 2019-01-12 14:09
Thanks for your quick answer.

For example, I go t the error when I try to hash this file:
[Test_Hash_Failed.txt](https://github.com/rokups/zinc/files/2752081/Test_Hash_Failed.txt)
with this command:
`zinc.exe hash source\Test_Hash_Failed.txt source\Test_Hash_Failed.txt.json`

**Closed as completed** 2019-01-12 15:14 UTC

**Comment by Catsy73** [comment] 2019-01-12 17:15
Thanks for your quick support!
All works well now!
